sonar.projectKey=JuanPinheiroFIAP_Lory
sonar.organization=juanpinheirofiap

sonar.sources=src 

sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/main.py,**/database.py,**/init_db.py,**/__init__.py